FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
 && apt-get -y install \
        gcc \
        git \
        libc6-dev \
        libglib2.0-dev \
        pkg-config \
        make \
        runc \
        curl