FROM ubuntu:bionic

RUN apt-get update \
 && apt-get -y install \
        curl \
        git \
        mercurial \
        make \
        binutils \
        bison \
        gcc \
        build-essential